server:
  port: 8080

app:
  credentials-path: C:\\w\\ws\\ext\\vision\\spiritual-craft-792-8b0436b690af.json
  storage-bucket: rasc-demo-vision

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

